version: 2.1
jobs:
  build:
    working_directory: ~/AndroidAppTemplate
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Fastlane update
          command: |
            bundle install
            bundle update fastlane
      - run:
          name: Lint Check
          command: |
            bundle exec fastlane lint
      - run:
          name: Run Tests
          command: |
            bundle exec fastlane test
      - run:
          name: Build Debug APK
          command: |
            bundle exec fastlane build_debug